name: Test

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.repository }} # For the tests to be able to publish current branch

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version-file: .nvmrc

      - name: Setup pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6
        with:
          run_install: true

      - name: Lint
        run: pnpm lint

      - name: Type check
        run: pnpm type-check

      - name: Build
        run: pnpm build

      - name: Setup Git # Only used by the Publish test
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"

      - name: Test
        run: pnpm test
